name: Rust-CI

# This workflow run tests and build for each push

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings          

      - name: Test
        run: |
          cargo check
          cargo test --all          

      - name: Build
        run: |
          rustup target add x86_64-unknown-linux-musl
          cargo build --release --target x86_64-unknown-linux-musl
      
      - name: Release
        run: |
          docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_TOKEN }}
          docker build . --file Dockerfile --tag potor10/sekai-client:$(date +%s)
          docker images
          docker image inspect client:latest
          docker run client:latest
          docker push potor10/sekai-client:client:latest 